name: app
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.5
  - pip
  - numpy
  - pandas
  - sqlalchemy
  - psycopg2
  - openpyxl
  - xlrd
  - streamlit
  - pip:
    # AI/ML and LangChain packages
    - langchain>=0.1.0
    - langchain-community>=0.0.20
    - langchain-openai
    - openai>=1.0.0
    - sentence-transformers
    - tenacity
    
    # Database packages
    - sqlmodel
    - psycopg2-binary
    
    # Configuration and utilities
    - dynaconf
    - pydantic>=2.0.0
    
    # Development tools
    - ruff
    
    # Web framework
    - streamlit>=1.28.0
    
    # Excel processing
    - openpyxl
    - xlrd