EXCEL_TABLE_NAME = "excel_table"

[GENERATOR]
AZURE_DEPLOYMENT = 'your_deployment_name' 
AZURE_ENDPOINT = "your_endpoint_url"
OPENAI_API_VERSION = "open_api_version"
TEMPERATURE = 0.01
MAX_TOKENS = 4096

[RDBMS]
NAME = 'postgresql'
USERNAME = 'your_postgres_username'
HOST = 'your_postgres_host'
PORT = 'your_postgres_port_number'
DATABASE_NAME = 'your_database_name'
